### ISSUE TITLE
Interface requests

### ISSUE THREAD

**Issue by samtwilson** [aparcar/valve-controller#1]
1. Please can the valve interface have a 'stop'' setting. When this is activated the program is paused and all valves remain in their existing state
2. Please can the valve interface have a default'' setting. When this is activated, all solenoid valves are returned to 0 and MPV1 is on state 2 and MPV2 is on state 3
3. Please can the valve interface have a manual interface which allows me to activate/deactivate a solenoid valve and rotate the MPV valves. It would be very useful if this is manual setting also allowed me to visually see the state of SV and MPV. This is already achieved when I run a program.

**Comment by aparcar** [comment]
All three interface changes were added. It's not infinity pretty (nor interface nor code) but it get the job done. Please let me know if any additional features are required. 

![image](https://user-images.githubusercontent.com/16000931/124413960-739d9880-dced-11eb-8c87-1a4a93c0ae07.png)
